# Generated by Django 5.2.9 on 2025-12-18 17:08

import django.db.models.deletion
from django.db import migrations, models
from uuid_extensions import uuid7


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PokemonType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid7,
                        editable=False,
                        help_text="UUIDv7 primary key (time-sortable)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Pokemon type name (e.g., fire, water, grass)", max_length=50, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Pokemon Type",
                "verbose_name_plural": "Pokemon Types",
                "db_table": "pokemon_types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid7,
                        editable=False,
                        help_text="UUIDv7 primary key (time-sortable)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("pokedex_number", models.PositiveIntegerField(help_text="National Pokedex number", unique=True)),
                ("name", models.CharField(help_text="Pokemon name", max_length=100, unique=True)),
                ("sprite_url", models.URLField(blank=True, help_text="URL to Pokemon sprite image", max_length=500)),
                ("base_hp", models.PositiveIntegerField(help_text="Base HP stat")),
                ("base_attack", models.PositiveIntegerField(help_text="Base Attack stat")),
                ("base_defense", models.PositiveIntegerField(help_text="Base Defense stat")),
                ("base_speed", models.PositiveIntegerField(help_text="Base Speed stat")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="When this Pokemon was added to the database"),
                ),
                (
                    "primary_type",
                    models.ForeignKey(
                        help_text="Primary Pokemon type",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pokemon_primary",
                        to="pokemon.pokemontype",
                    ),
                ),
                (
                    "secondary_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Secondary Pokemon type (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pokemon_secondary",
                        to="pokemon.pokemontype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pokemon",
                "verbose_name_plural": "Pokemon",
                "db_table": "pokemon",
                "ordering": ["pokedex_number"],
                "indexes": [
                    models.Index(fields=["primary_type"], name="pokemon_primary_type_idx"),
                    models.Index(fields=["secondary_type"], name="pokemon_secondary_type_idx"),
                    models.Index(fields=["name"], name="pokemon_name_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TypeEffectiveness",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid7,
                        editable=False,
                        help_text="UUIDv7 primary key (time-sortable)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "multiplier",
                    models.FloatField(
                        choices=[
                            (2.0, "Super Effective (2x)"),
                            (1.0, "Normal (1x)"),
                            (0.5, "Not Very Effective (0.5x)"),
                            (0.0, "No Effect (0x)"),
                        ],
                        default=1.0,
                        help_text="Damage multiplier: 2.0=super effective, 0.5=not very effective, 0=no effect",
                    ),
                ),
                (
                    "attacker_type",
                    models.ForeignKey(
                        help_text="The attacking Pokemon's type",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attacking_effectiveness",
                        to="pokemon.pokemontype",
                    ),
                ),
                (
                    "defender_type",
                    models.ForeignKey(
                        help_text="The defending Pokemon's type",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="defending_effectiveness",
                        to="pokemon.pokemontype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Type Effectiveness",
                "verbose_name_plural": "Type Effectivenesses",
                "db_table": "type_effectiveness",
                "indexes": [models.Index(fields=["attacker_type", "defender_type"], name="type_matchup_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("attacker_type", "defender_type"), name="unique_type_matchup")
                ],
            },
        ),
    ]
