# Generated by Django 5.2.9 on 2025-12-19 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from uuid_extensions import uuid7


class Migration(migrations.Migration):
    dependencies = [
        ("pokemon", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerPokemon",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid7,
                        editable=False,
                        help_text="UUIDv7 primary key (time-sortable)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="When the player obtained this Pokemon"),
                ),
            ],
            options={
                "verbose_name": "Player Pokemon",
                "verbose_name_plural": "Player Pokemon",
                "db_table": "player_pokemon",
                "ordering": ["-id"],
            },
        ),
        migrations.AlterModelOptions(
            name="pokemon",
            options={"verbose_name": "Pokemon", "verbose_name_plural": "Pokemon"},
        ),
        migrations.RemoveIndex(
            model_name="pokemon",
            name="pokemon_primary_type_idx",
        ),
        migrations.RemoveIndex(
            model_name="pokemon",
            name="pokemon_secondary_type_idx",
        ),
        migrations.RemoveIndex(
            model_name="pokemon",
            name="pokemon_name_idx",
        ),
        migrations.RemoveIndex(
            model_name="typeeffectiveness",
            name="type_matchup_idx",
        ),
        migrations.AddField(
            model_name="playerpokemon",
            name="player",
            field=models.ForeignKey(
                help_text="The player who owns this Pokemon",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_pokemon",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="playerpokemon",
            name="pokemon",
            field=models.ForeignKey(
                help_text="The Pokemon owned by the player",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_pokemon",
                to="pokemon.pokemon",
            ),
        ),
        migrations.AddConstraint(
            model_name="playerpokemon",
            constraint=models.UniqueConstraint(fields=("player", "pokemon"), name="unique_player_pokemon"),
        ),
    ]
