# Generated by Django 5.2.9 on 2025-12-19 14:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pokemon", "0002_playerpokemon_alter_pokemon_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemon",
            name="players",
            field=models.ManyToManyField(
                help_text="Players who own this Pokemon",
                related_name="pokemons",
                through="pokemon.PlayerPokemon",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
