# Generated by Django 5.2.9 on 2025-12-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pokemon", "0003_pokemon_players"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerpokemon",
            name="deleted_at",
            field=models.DateTimeField(blank=True, help_text="When this Pokemon was removed from the team", null=True),
        ),
    ]
