# Generated by Django 5.2.9 on 2025-12-19 16:31

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pokemon", "0004_playerpokemon_deleted_at"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="playerpokemon",
            managers=[
                ("with_trash", django.db.models.manager.Manager()),
            ],
        ),
    ]
