# Generated by Django 5.2.9 on 2025-12-19 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from uuid_extensions import uuid7


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pokemon", "0005_alter_playerpokemon_managers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Battle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid7,
                        editable=False,
                        help_text="UUIDv7 primary key (time-sortable)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        help_text="Battle status",
                        max_length=20,
                    ),
                ),
                ("turn_number", models.PositiveIntegerField(default=1, help_text="Current turn number")),
                ("player1_current_hp", models.PositiveIntegerField(help_text="Player 1's current HP")),
                ("player2_current_hp", models.PositiveIntegerField(help_text="Player 2's current HP")),
                ("player1_potions", models.PositiveIntegerField(default=3, help_text="Player 1's remaining potions")),
                (
                    "player1_x_attack",
                    models.PositiveIntegerField(default=1, help_text="Player 1's remaining X-Attack items"),
                ),
                (
                    "player1_x_defense",
                    models.PositiveIntegerField(default=1, help_text="Player 1's remaining X-Defense items"),
                ),
                ("player2_potions", models.PositiveIntegerField(default=3, help_text="Player 2's remaining potions")),
                (
                    "player2_x_attack",
                    models.PositiveIntegerField(default=1, help_text="Player 2's remaining X-Attack items"),
                ),
                (
                    "player2_x_defense",
                    models.PositiveIntegerField(default=1, help_text="Player 2's remaining X-Defense items"),
                ),
                (
                    "player1_attack_boost",
                    models.PositiveIntegerField(default=0, help_text="Player 1's remaining attack boost turns"),
                ),
                (
                    "player1_defense_boost",
                    models.PositiveIntegerField(default=0, help_text="Player 1's remaining defense boost turns"),
                ),
                (
                    "player2_attack_boost",
                    models.PositiveIntegerField(default=0, help_text="Player 2's remaining attack boost turns"),
                ),
                (
                    "player2_defense_boost",
                    models.PositiveIntegerField(default=0, help_text="Player 2's remaining defense boost turns"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="When the battle was created")),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, help_text="When the battle was completed", null=True),
                ),
                (
                    "current_turn_player",
                    models.ForeignKey(
                        help_text="Player whose turn it is",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="current_turn_battles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "player1",
                    models.ForeignKey(
                        help_text="First player in the battle",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="battles_as_player1",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "player1_pokemon",
                    models.ForeignKey(
                        help_text="Player 1's Pokemon in this battle",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="pokemon.playerpokemon",
                    ),
                ),
                (
                    "player2",
                    models.ForeignKey(
                        help_text="Second player in the battle (usually AI)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="battles_as_player2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "player2_pokemon",
                    models.ForeignKey(
                        help_text="Player 2's Pokemon in this battle",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="pokemon.playerpokemon",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Winner of the battle (null if not completed)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="won_battles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Battle",
                "verbose_name_plural": "Battles",
                "db_table": "battles",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="BattleTurn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid7,
                        editable=False,
                        help_text="UUIDv7 primary key (time-sortable)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("turn_number", models.PositiveIntegerField(help_text="The turn number this action occurred on")),
                (
                    "action",
                    models.CharField(
                        choices=[("attack", "Attack"), ("defend", "Defend")],
                        help_text="Action taken (attack or defend)",
                        max_length=10,
                    ),
                ),
                (
                    "damage",
                    models.PositiveIntegerField(default=0, help_text="Damage dealt in this turn (0 if defend or miss)"),
                ),
                ("is_critical", models.BooleanField(default=False, help_text="Whether this was a critical hit")),
                (
                    "is_super_effective",
                    models.BooleanField(default=False, help_text="Whether this was super effective"),
                ),
                ("message", models.CharField(help_text="Turn message/description", max_length=255)),
                (
                    "battle",
                    models.ForeignKey(
                        help_text="The battle this turn belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turns",
                        to="battles.battle",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        help_text="The player who made this action",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="battle_turns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Battle Turn",
                "verbose_name_plural": "Battle Turns",
                "db_table": "battle_turns",
                "ordering": ["turn_number", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="battle",
            index=models.Index(fields=["player1", "status"], name="battle_player1_status_idx"),
        ),
        migrations.AddIndex(
            model_name="battle",
            index=models.Index(fields=["player2", "status"], name="battle_player2_status_idx"),
        ),
        migrations.AddIndex(
            model_name="battle",
            index=models.Index(fields=["status", "-created_at"], name="battle_status_created_idx"),
        ),
        migrations.AddIndex(
            model_name="battleturn",
            index=models.Index(fields=["battle", "turn_number"], name="battle_turn_battle_turn_idx"),
        ),
    ]
