# Generated by Django 5.2.9 on 2025-12-18 15:43

from django.db import migrations, models
from uuid_extensions import uuid7


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid7,
                        editable=False,
                        help_text="UUIDv7 primary key (time-sortable)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "username",
                    models.CharField(help_text="Required. 150 characters or fewer.", max_length=150, unique=True),
                ),
                ("wins", models.PositiveIntegerField(default=0, help_text="Total number of battles won")),
                ("losses", models.PositiveIntegerField(default=0, help_text="Total number of battles lost")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="When the player account was created"),
                ),
                ("is_active", models.BooleanField(default=True, help_text="Whether this player account is active")),
                (
                    "is_staff",
                    models.BooleanField(default=False, help_text="Whether the player can access the admin site"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Player",
                "verbose_name_plural": "Players",
                "db_table": "players",
                "ordering": ["-id"],
                "indexes": [models.Index(fields=["-wins", "losses"], name="player_scoreboard_idx")],
            },
        ),
    ]
