# Generated by Django 5.2.9 on 2025-12-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0001_initial"),
        ("pokemon", "0002_playerpokemon_alter_pokemon_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="pokemons",
            field=models.ManyToManyField(
                help_text="Pokemon owned by this player",
                related_name="players",
                through="pokemon.PlayerPokemon",
                to="pokemon.pokemon",
            ),
        ),
    ]
