# Generated by Django 5.2.9 on 2025-12-19 14:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0002_player_pokemons"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="pokemons",
        ),
    ]
