# Generated by Django 5.2.9 on 2025-12-19 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0003_remove_player_pokemons"),
        ("pokemon", "0005_alter_playerpokemon_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="active_pokemon",
            field=models.ForeignKey(
                blank=True,
                help_text="The active Pokemon for battles",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_for_players",
                to="pokemon.playerpokemon",
            ),
        ),
    ]
